apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: result-app-service
    app: result-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: redis
    app: voting-app